/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/_game'
import { Route as GameIndexRouteImport } from './routes/_game.index'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as GameRCodeRouteImport } from './routes/_game.r.$code'

const GameRoute = GameRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRoute,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRCodeRoute = GameRCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GameIndexRoute
  '/api/rtc': typeof ApiRtcRoute
  '/r/$code': typeof GameRCodeRoute
}
export interface FileRoutesByTo {
  '/api/rtc': typeof ApiRtcRoute
  '/': typeof GameIndexRoute
  '/r/$code': typeof GameRCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_game': typeof GameRouteWithChildren
  '/api/rtc': typeof ApiRtcRoute
  '/_game/': typeof GameIndexRoute
  '/_game/r/$code': typeof GameRCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/rtc' | '/r/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/rtc' | '/' | '/r/$code'
  id: '__root__' | '/_game' | '/api/rtc' | '/_game/' | '/_game/r/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GameRoute: typeof GameRouteWithChildren
  ApiRtcRoute: typeof ApiRtcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game/': {
      id: '/_game/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRoute
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game/r/$code': {
      id: '/_game/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof GameRCodeRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GameIndexRoute: typeof GameIndexRoute
  GameRCodeRoute: typeof GameRCodeRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameIndexRoute: GameIndexRoute,
  GameRCodeRoute: GameRCodeRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GameRoute: GameRouteWithChildren,
  ApiRtcRoute: ApiRtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
